name: "Publish"
on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    permissions:
      contents: write
      packages: write
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --aarch64 --amd64 \
          --target caddy-webhook \
          --docker-hub ghcr.io/caraar12345/caddy-webhook/hass-caddy-webhook
