name: "Test HA addon build"

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --aarch64 --amd64 \
          --target caddy-webhook \
          --docker-hub ghcr.io/caraar12345/caddy-webhook \
          --image hass-{arch}